version: '2'
services:
    zookeeper1:
      image: 'docker.io/zookeeper'
      container_name: 'zookeeper1'
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
        TZ: "Asia/Shanghai"
      ports:
        - 2181:2181

    zookeeper2:
      image: 'docker.io/zookeeper'
      container_name: 'zookeeper2'
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        ZOO_MY_ID: 2
        ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper3:2888:3888
        TZ: "Asia/Shanghai"
      ports:
        - 2182:2181

    zookeeper3:
      image: 'docker.io/zookeeper'
      container_name: 'zookeeper3'
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        ZOO_MY_ID: 3
        ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=0.0.0.0:2888:3888
        TZ: "Asia/Shanghai"
      ports:
        - 2183:2181
  
    zkui:
      image: 'muidea.ai/zkui'
      container_name: 'zkui'
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro      
      environment:
        ZK_SERVER: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
        TZ: "Asia/Shanghai"
      ports:
        - 9090:9090

    kafka1:
      image: 'muidea.ai/kafka'
      container_name: 'kafka1'
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        BROKER_ID: 1
        ZOO_SERVERS: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
        ADV_LISTENERS: PLAINTEXT://kafka1:9092
        TZ: "Asia/Shanghai"
      ports:
        - 9091:9092

    kafka2:
      image: 'muidea.ai/kafka'
      container_name: 'kafka2'
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        BROKER_ID: 2
        ZOO_SERVERS: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
        ADV_LISTENERS: PLAINTEXT://kafka2:9092
        TZ: "Asia/Shanghai"
      ports:
        - 9092:9092

    kafka3:
      image: 'muidea.ai/kafka'
      container_name: 'kafka3'
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        BROKER_ID: 3
        ZOO_SERVERS: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
        ADV_LISTENERS: PLAINTEXT://kafka3:9092
        TZ: "Asia/Shanghai"
      ports:
        - 9093:9092

    rtdservice:
      image: 'muidea.ai/rtdservice'
      container_name: 'rtdservice'
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        BROKER_LIST: kafka1:9092,kafka2:9092,kafka3:9092
        TZ: "Asia/Shanghai"
      ports:
        - 8010:8010

    hisservice:
      image: 'muidea.ai/hisservice'
      container_name: 'hisservice'
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        BROKER_LIST: kafka1:9092,kafka2:9092,kafka3:9092
        TOPIC_NAME: rtddata
        TZ: "Asia/Shanghai"

networks:
  muidea-ai:
 